### ISSUE TITLE
corrupts pngs created by paint.net.

### ISSUE THREAD

**Issue by lobsterfran** [MaxxWyndham/Breckfest#1]
Sometimes, not always, breckfest creates a corrupted mess when pngs are converted. If I take the png file created by paint.net, open it in MSPaint, then save it again without making any changes, breckfest will happily convert them 100% of the time. MSPaint strips out transparency, so I assume this is where the issue lies.
The first image is one that Breckfest corrupts for me.
![test](https://cloud.githubusercontent.com/assets/13404274/8766158/b05260ae-2e24-11e5-8cc8-206b4b023ff4.png)
The second image is what the corrupted file looks like if you run the bmap back through breckfest.
![test x dxt5](https://cloud.githubusercontent.com/assets/13404274/8766171/0bce7418-2e25-11e5-9252-25f41c832212.png)

**Comment by MaxxWyndham** [comment]
@lobsterfran cheers for this.  Could you do a quick test for me?  Open that PNG in paint.net, do a save as png and rather than leaving "bit depth" as "auto-detect" could you select "32-bit"?

**Comment by lobsterfran** [comment]
Yup, that was the issue. Thanks.
