### ISSUE TITLE
Anti-virus false positive

### ISSUE THREAD

**Issue by Flash313** [MaxxWyndham/Breckfest#4]
my anti-virus protection is blocking this and telling me it's a virus

**Comment by MaxxWyndham** [comment]
Crikey, sorry chap, I completely missed this issue.

I have no idea why your anti-virus would consider this a virus.  I honestly couldn't write such sophisticated code!

Let me know if this is still a thing and I can try to work something out

**Comment by MaxxWyndham** [comment]
Mazay has suggest this is due to Fody compressing the archive, supplied some xml to prevent this occuring AND pointed me towards a site to test the exe.

I should have this licked in the next release
